#playbook to copy ssh key to managed nodes

- hosts: all

  remote_user: ansible
  become: yes
  become_method: sudo 
  tasks:

    - name: Copy file with owner and permissions
  
      copy:
        src: /home/centos/.ssh/id_rsa.pub
        dest: /home/ansible/.ssh/
        owner: ansible
        group: ansible
        mode: '0644'
