---
- hosts: demo
 
  tasks:

    - name: Set authorized key taken from file
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/centos/.ssh/id_rsa.pub') }}"

